# src/config.py

DEFAULT_WIDTH = 64
DEFAULT_HEIGHT = 48
DEFAULT_GLYPHS = 256
DEFAULT_BLOCK_SIZE = (8, 8)
DEFAULT_OPTIMIZE_EPOCHS = 500
DEFAULT_OPTIMIZE_LR = 0.002
DEFAULT_OPTIMIZE_BATCH_SIZE = 48
DEFAULT_FPS = 30.0 # Default FPS if not detected from video or specified by user
